---
title: "Mini Project Academic Performance Analysis"
author: "Deni Permana - Diaz Fahreza Akbar"
date: "2024-11-24"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Exploratory Data Analysis


## 0. Import Library
Library yang akan digunakan

```{r}
library(readr)  # Untuk membaca data dengan cepat dari berbagai format seperti CSV
library(tidyverse)  # Sekumpulan paket terintegrasi untuk analisis data yang mendukung tidy data
library(dplyr)  # Untuk manipulasi data dengan sintaks yang bersih dan intuitif
```

## 1. Import Dataset

Dataset yang akan digunakan

```{r}
# 1. Student Mat
student_mat_data <- read_delim("resources/dataset/student-mat.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)

# 2. Student Por
student_por_data <- read_delim("resources/dataset/student-por.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)
```

## 2. Exploration Data Awal

```{r}
# 1. Display Data
head(student_mat_data, 5)
head(student_por_data, 5)
```

```{r}
# 2. Display Data Structure
str(student_mat_data)
str(student_por_data)
```

```{r}
# 3. Descriptive Stats
summary(student_mat_data)
summary(student_por_data)
```

## 3. Cleaning Data

```{r}
# 1. Merge Datasets
student_mat_data$course <- "Math"
student_por_data$course <- "Portuguese"
student_data <- bind_rows(student_mat_data, student_por_data)
```

```{r}
# 2. Select Columns
selected_columns <- c("sex", "age", "address", "studytime", "failures", 
                      "schoolsup", "famsup", "freetime", "goout", "romantic", 
                      "G1", "G2", "G3")
student_data <- student_data[, selected_columns]
```

```{r}
# 3. Pre-Process Categorical Data
student_data <- student_data %>%
  mutate(
    sex = ifelse(sex == "F", 0, 1),
    address = ifelse(address == "U", 0, 1),
    schoolsup = ifelse(schoolsup == "no", 0, 1),
    famsup = ifelse(famsup == "no", 0, 1),
    romantic = ifelse(romantic == "no", 0, 1)
  )
```

```{r}
# 4. Handle Empty Values
student_data <- na.omit(student_data)
```

```{r}
# 6. Display Cleared Data
head(student_data, 5)
```

## 4. Exploration Data Akhir

```{r}

```

